spring:
  main.banner-mode: off
  application:
    name: ingestion
  datasource:
    url: jdbc:postgresql://localhost:5431/electrix
    username: electrix
    password: electrix
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    default-schema: electrix

ingestion:
  clickhouse:
    url: jdbc:clickhouse://localhost:8123/default
    user: electrix
    password: electrix
  data:
    consommation:
      brut_national: https://odre.opendatasoft.com/api/explore/v2.1/catalog/datasets/consommation-quotidienne-brute/exports/parquet
      brut_regional: https://odre.opendatasoft.com/api/explore/v2.1/catalog/datasets/consommation-quotidienne-brute-regionale/exports/parquet
      eco2mix_nationale: https://odre.opendatasoft.com/api/explore/v2.1/catalog/datasets/eco2mix-national-cons-def/exports/parquet
      eco2mix_regionale: https://odre.opendatasoft.com/api/explore/v2.1/catalog/datasets/eco2mix-regional-cons-def/exports/parquet
