spring:
  application:
    name: ingestion
  datasource:
    url: jdbc:postgresql://localhost:5431/electrix
    username: electrix
    password: electrix
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    default-schema: electrix

ingestion:
  clickhouse:
    url: jdbc:clickhouse://localhost:8123/default
    user: electrix
    password: electrix
  data:
    consommation:
      brut: classpath:data/consommation-quotidienne-brute.parquet
      nationale: classpath:data/eco2mix-national-cons-def.parquet
      regionale: classpath:data/eco2mix-regional-cons-def.parquet
